### ISSUE TITLE
Battery Won't Charge

### ISSUE THREAD

**Issue by Squidman32** [sparkfun/Qduino_Mini_SFE#4]
I am not able to get my 3.7V 2000mAh patter to charge on my Qduino.  I'm brand new to DIY electronics, so may be missing something. I plugged in board to usb and plugged the battery into the board and left it over night.  It is still at 0% when I check it with qduino FuelGage program, and the battery doesn't power the board on its own.  Is there a way I can do a factory reset or update firmware to see if thats the issue?

**Comment by bboyho** [comment]
Hi,

I just noticed your question when browsing this GitHub repository. This seems more like a technical support related question. The Qduino Mini usually is tested and by quality control before it is packaged and sent out. The board has a dedicated LiPo charger set to 100mA by default but I do not think that has anything to do with your LiPo not charging. The firmware has nothing to do with configuring the charge rate but you can monitor the LiPo battery.

If you are using a [3.7V/2000mAh LiPo battery](https://www.sparkfun.com/products/13855) with a built-in protection circuit, it's possible the battery's protection circuit kicked in when if it is under the minimum voltage preventing it from being charged. I would also check your USB cable. If you have further issues, you may want to check with our [technical support](https://www.sparkfun.com/technical_assistance) if you have not already.

**Comment by Squidman32** [comment]
Thanks for the help!  Turns out the positive/negative terminals on the batter were the opposite of those on the Qduino.  I manually swapped them around in the jack that came with the battery and now it all works no problem.

**Comment by bboyho** [comment]
Cool. That's a first that I have seen with the battery pins reversed. I'm glad to hear that you got it figured out!
